name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Configure Poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Build release distributions
        run: |
          python -m poetry build
        # This will create a dist/ folder with .tar.gz and .whl files

      - name: Configure Poetry
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI

      - name: Publish package to PyPI
        run: |
          python -m poetry publish
